# Generated by Django 5.1.4 on 2025-02-12 21:43

import managementdataset.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=managementdataset.models.PostImageStorage(), upload_to=managementdataset.models.image_file_name, verbose_name='Imagen')),
            ],
        ),
    ]
