# Generated by Django 5.1.4 on 2025-02-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementdataset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdataset',
            name='descriptors',
            field=models.BinaryField(blank=True, null=True, verbose_name='Image descriptors'),
        ),
        migrations.AddField(
            model_name='imgdataset',
            name='keypoints',
            field=models.BinaryField(blank=True, null=True, verbose_name='Image keypoints'),
        ),
    ]
