# Generated by Django 5.1.4 on 2025-04-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementpacient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
