# Generated by Django 5.1.4 on 2025-04-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementpacient', '0002_alter_history_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='doctor_notes',
        ),
    ]
