# Generated by Django 5.1.6 on 2025-04-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementpacient', '0003_remove_history_doctor_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
    ]
